name: release test

on: 
  push:
  # Sequence of patterns matched against refs/heads
    branches:    
      - main
      - test
      - 'test'
    # Sequence of patterns matched against refs/tags
    tags:        
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Release.txt
